# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scada_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging_file', models.CharField(default='../scada.log', max_length=255, verbose_name='path of the logging file')),
                ('logging_level', models.PositiveSmallIntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG'), (0, 'NOTSET')], default=40, verbose_name='Logging level')),
                ('server_port', models.PositiveSmallIntegerField(default=8888, verbose_name='scada daemon server port')),
                ('server_password', models.CharField(default='ca93107ec58ddcb984eb210bad726925', editable=False, max_length=128, verbose_name='password needed to end de scada daemon')),
            ],
        ),
        migrations.CreateModel(
            name='variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='unique name of the variable')),
                ('default_value', models.FloatField()),
                ('direction', models.CharField(choices=[('input', 'is a signal that is sampled'), ('output', 'is a signal that is generated'), ('dummy', 'is a signal without type')], max_length=20, verbose_name='direction of the variable')),
                ('name_gui', models.CharField(blank=True, max_length=150, verbose_name='name of the variable user friendly')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='descripcion')),
                ('origin', models.TextField(blank=True, max_length=150, verbose_name='description of the hardware that generate/measure this variable')),
                ('destination', models.TextField(blank=True, max_length=150, verbose_name='What is this variable for?')),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.variable')),
                ('nchannel', models.PositiveIntegerField()),
            ],
            bases=('base.variable',),
        ),
    ]
