# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datalogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_time', models.FloatField(default=60.0, verbose_name='Sampling time [s]')),
                ('data_path', models.CharField(max_length=255, verbose_name='Path where the data are saved')),
            ],
        ),
    ]
