# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='source_on_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the source', max_length=64, verbose_name='Name of the source')),
                ('flow_off', models.FloatField(verbose_name='flow if it is off')),
                ('flow_on', models.FloatField(verbose_name='flow if it is on')),
                ('flow_variable', models.ForeignKey(help_text='the app will save the value of the flow in this variable in the realtime database', on_delete=django.db.models.deletion.CASCADE, related_name='flow_variable', to='base.variable')),
                ('input_variable', models.ForeignKey(help_text='the source is on when someone writes 1.0 in this variable, off if 0.0', on_delete=django.db.models.deletion.CASCADE, related_name='input_variable', to='base.variable')),
            ],
        ),
    ]
