# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='float_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of the float sensor')),
                ('switch_volume', models.FloatField()),
                ('switch_logic', models.BooleanField(choices=[(True, 'The float sensor is true when the level reach the sensor level'), (False, 'The float sensor is false when the level reach the sensor level')])),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank', to='tank.tank')),
            ],
        ),
    ]
