# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='electrovalve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of the electrovalve')),
                ('flow_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_variable', to='base.variable')),
                ('input_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_variable', to='base.variable')),
            ],
        ),
    ]
