# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='simulated_variable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.variable')),
                ('simulation_class', models.CharField(default='mezzanine_scada.hardware.simulated.constantsimulation', help_text='is the class path where the simulationclass is in', max_length=400)),
                ('simulation_class_kwargs', models.CharField(default='', help_text='arguments in json format will be passed as kwargs while the \n                                                            init of the process instance, example: \n                                                            {"keywordA":"value1", "keywordB":7}', max_length=400)),
                ('sampling_time', models.FloatField(default=10.0, verbose_name='Sampling time')),
            ],
            bases=('base.variable',),
        ),
    ]
