# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulated_variable',
            name='simulation_class',
            field=models.CharField(default='mezzanine_scada.hardware.simulated.simulatedclasses.constantsimulation', help_text='is the class path where the simulationclass is in', max_length=400),
        ),
        migrations.AlterField(
            model_name='simulated_variable',
            name='simulation_class_kwargs',
            field=models.CharField(default='', help_text='arguments in json format for the class. {"value":1.0 } for instance', max_length=400),
        ),
    ]
