# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of the tank')),
                ('maximum_volume', models.FloatField()),
                ('initial_volume', models.FloatField()),
                ('loop_time', models.FloatField()),
                ('input_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_flow', to='base.variable')),
                ('output_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_flow', to='base.variable')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='base.variable')),
            ],
        ),
    ]
